FROM python:3.10-alpine

EXPOSE 9000/tcp

WORKDIR /root
COPY requirements.txt /root/requirements.txt
COPY websocket /root
RUN apk add --no-cache alpine-sdk openssl-dev python3-dev bsd-compat-headers libffi-dev \
	&& pip install -r requirements.txt \
	&& rm -rf /root/.cache

ENV TZ=Asia/Shanghai
CMD [ "python", "server.py" ]